# Generated by Django 5.1.7 on 2025-03-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
