# Generated by Django 4.2.13 on 2025-03-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_teammember_alter_team_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='register_completed',
            field=models.BooleanField(default=False),
        ),
    ]
