# Generated by Django 4.2.13 on 2025-03-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_team_register_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
    ]
