# Generated by Django 5.1.7 on 2025-03-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='varification_completed',
            field=models.BooleanField(default=False),
        ),
    ]
