# Generated by Django 5.1.7 on 2025-03-23 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_team_varification_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='varification_completed',
            new_name='verification_completed',
        ),
    ]
