# Generated by Django 5.1.7 on 2025-03-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_varification_completed_team_verification_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='leader',
            field=models.BooleanField(default=False),
        ),
    ]
