# Generated by Django 5.1.7 on 2025-03-25 01:04

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_teammember_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='payment',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.Team.payment_image_upload_to),
        ),
        migrations.AddField(
            model_name='teammember',
            name='major',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='student_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='university',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
