# Generated by Django 5.1.7 on 2025-03-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_teammember_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='student_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
