# Generated by Django 5.1.7 on 2025-03-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_team_payment_teammember_major_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
