# Generated by Django 5.1.7 on 2025-03-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_staffmember_description_staffmember_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='payment',
        ),
        migrations.AddField(
            model_name='team',
            name='payment_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
