# Generated by Django 5.1.7 on 2025-03-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_team_payment_team_payment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
    ]
