# Generated by Django 5.1.7 on 2025-03-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_teammember_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='github',
        ),
        migrations.AddField(
            model_name='staffmember',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
    ]
