# Generated by Django 5.1.7 on 2025-03-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_teammember_github_staffmember_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='github',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
