# Generated by Django 4.2.13 on 2025-03-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_staffmember_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer.', max_length=150, unique=True),
        ),
    ]
